name: manipulando_dados
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-300.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.2
  path: ^1.8.3
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
